# Generated by Django 5.2.12 on 2026-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_update_price_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_stripe_webhook_event',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
