# Generated by Django 5.2.7 on 2026-02-10 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0002_cvdocument_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('current_role', models.CharField(blank=True, default='', max_length=255)),
                ('seniority_level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal')], default='', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('skill_levels', models.JSONField(blank=True, default=dict)),
                ('education', models.JSONField(blank=True, default=list)),
                ('companies', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hr_summary', models.TextField(blank=True, default='')),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='cv.cvdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_candidate_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='full_time', max_length=20)),
                ('seniority_level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal')], default='mid', max_length=20)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('optional_skills', models.JSONField(blank=True, default=list)),
                ('years_of_experience_required', models.PositiveIntegerField(default=0)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('languages_required', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('requirements_description', models.TextField(blank=True, default='')),
                ('nice_to_have', models.TextField(blank=True, default='')),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('avg_match_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_job_position',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFitResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('overall_match', models.PositiveIntegerField(blank=True, null=True)),
                ('skill_match', models.PositiveIntegerField(blank=True, null=True)),
                ('experience_match', models.PositiveIntegerField(blank=True, null=True)),
                ('seniority_match', models.PositiveIntegerField(blank=True, null=True)),
                ('education_match', models.PositiveIntegerField(blank=True, null=True)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('interview_questions', models.JSONField(blank=True, default=list)),
                ('fit_recommendation', models.CharField(blank=True, choices=[('strong_fit', 'Strong Fit'), ('good_fit', 'Good Fit'), ('moderate_fit', 'Moderate Fit'), ('weak_fit', 'Weak Fit'), ('not_recommended', 'Not Recommended')], default='', max_length=20)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('openai_tokens_used', models.PositiveIntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_results', to='recruitment.candidateprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fit_results', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_results', to='recruitment.jobposition')),
            ],
            options={
                'db_table': 'recruitment_job_fit_result',
                'ordering': ['-overall_match', '-created_at'],
                'unique_together': {('candidate', 'position')},
            },
        ),
    ]
