# Generated by Django 5.2.7 on 2026-02-13 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfitresult',
            name='fit_recommendation',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('strong_fit', 'Strong Fit'), ('good_fit', 'Good Fit'), ('moderate_fit', 'Moderate Fit'), ('weak_fit', 'Weak Fit'), ('poor', 'Poor'), ('not_recommended', 'Not Recommended')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='RequirementMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_text', models.TextField()),
                ('requirement_type', models.CharField(choices=[('skill_required', 'Required Skill'), ('skill_optional', 'Optional Skill'), ('responsibility', 'Responsibility'), ('experience', 'Experience'), ('language', 'Language')], max_length=20)),
                ('match_percentage', models.FloatField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('weight', models.FloatField(default=1.0)),
                ('fit_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_matches', to='recruitment.jobfitresult')),
            ],
            options={
                'db_table': 'recruitment_requirement_match',
                'ordering': ['-match_percentage'],
            },
        ),
    ]
