# Generated by Django 5.2.7 on 2026-02-13 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_jobfitresult_fit_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(choices=[('experience', 'Doswiadczenie zawodowe'), ('education', 'Wyksztalcenie'), ('languages', 'Znajomosc jezykow'), ('skills', 'Umiejetnosci'), ('interests', 'Zainteresowania')], max_length=50)),
                ('score', models.FloatField(default=0)),
                ('weight', models.FloatField(default=1.0)),
                ('analysis', models.TextField(blank=True, default='')),
                ('section_content', models.TextField(blank=True, default='')),
                ('fit_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='recruitment.jobfitresult')),
            ],
            options={
                'db_table': 'recruitment_section_score',
                'ordering': ['-score'],
                'unique_together': {('fit_result', 'section_name')},
            },
        ),
    ]
