# Generated by Django 5.2.7 on 2026-02-09 01:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('structure_score', models.PositiveIntegerField(blank=True, null=True)),
                ('readability_score', models.PositiveIntegerField(blank=True, null=True)),
                ('professionalism_score', models.PositiveIntegerField(blank=True, null=True)),
                ('ats_score', models.PositiveIntegerField(blank=True, null=True)),
                ('sections_detected', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('percentile_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('openai_tokens_used', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cv.cvdocument')),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='accounts.guestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('generic_description', 'Too Generic Descriptions'), ('missing_specifics', 'Missing Specifics'), ('missing_keywords', 'Missing Keywords'), ('structural', 'Structural Issues'), ('formatting', 'Formatting Issues'), ('grammar', 'Grammar / Language'), ('length', 'Length Issues'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('affected_text', models.TextField(blank=True, default='')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'analysis_problem',
                'ordering': ['severity', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('rewrite', 'Rewrite'), ('skill', 'Develop Skill'), ('structure', 'Restructure'), ('career', 'Career Advice')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('suggested_text', models.TextField(blank=True, default='')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'analysis_recommendation',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='RewrittenSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=30)),
                ('original_text', models.TextField()),
                ('rewritten_text', models.TextField()),
                ('improvement_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrites', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'analysis_rewritten_section',
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('current_level', models.CharField(blank=True, default='', max_length=50)),
                ('recommended_level', models.CharField(blank=True, default='', max_length=50)),
                ('importance', models.CharField(default='medium', max_length=20)),
                ('learning_resources', models.TextField(blank=True, default='')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'analysis_skill_gap',
            },
        ),
    ]
