# Generated by Django 5.2.7 on 2026-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
