# Generated by Django 5.2.7 on 2026-02-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='professionalism_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='readability_score',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='structure_score',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SectionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing'), ('weak', 'Weak')], default='present', max_length=10)),
                ('analysis_text', models.TextField(blank=True, default='')),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_analyses', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'analysis_section_analysis',
                'ordering': ['section'],
            },
        ),
    ]
