# Generated by Django 5.2.7 on 2026-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_analysisresult_ats_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('partial', 'Partial Results'), ('pending_ai', 'Pending AI'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
