# Generated by Django 5.2.12 on 2026-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysisresult_security_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
