# Generated by Django 5.2.12 on 2026-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_analysisresult_risk_score_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='injection_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
