"""analysis/services/text_cleaner.py - Czyszczenie tekstu CV przed wysłaniem do AI.

Optymalizacja: mniejszy input = szybsza odpowiedź AI.
Bezpieczeństwo: sanityzacja i wykrywanie prób Prompt Injection zawartych w CV.
Usuwa: HTML, JS, base64, zero-width, stopki, powtórzenia. Skraca do max 4000 znaków.
"""

import logging
import re

logger = logging.getLogger(__name__)


class TextCleaner:
    """Czyści i przygotowuje tekst CV do analizy AI."""

    # Wzorce szumu (stopki, numery stron)
    NOISE_PATTERNS = [
        r'Page \d+ of \d+',
        r'Strona \d+ z \d+',
        r'^\s*\d+\s*$',
        r'(?i)curriculum vitae\s*$',
        r'(?i)resume\s*$',
        r'(?i)^generated by.*$',
        r'(?i)^powered by.*$',
        r'(?i)^confidential\s*$',
    ]

    # Wzorce Prompt Injection — wykrywane i flagowane (nie blokują analizy)
    INJECTION_PATTERNS = [
        (r'(?i)ignore\s+(all\s+)?(previous|prior|above)\s+instructions?', 'ignore_instructions'),
        (r'(?i)you\s+are\s+now\s+(an?\s+)?(admin|assistant|system|gpt|ai|bot)', 'role_escalation'),
        (r'(?i)(print|show|reveal|output|display|repeat)\s+(your\s+)?(system\s+)?prompt', 'prompt_extraction'),
        (r'(?i)(reveal|show|print|leak|output)\s+.{0,30}(api\s*key|secret|password|token|config)', 'secret_extraction'),
        (r'(?i)act\s+as\s+(if\s+)?(you\s+(are|were)\s+)?(an?\s+)?(admin|root|superuser)', 'role_escalation'),
        (r'(?i)(execute|run|eval|call)\s*[:\-]\s*\S', 'code_execution'),
        (r'(?i)(curl|wget)\s+https?://', 'external_request'),
        (r'(?i)new\s+instructions?\s*[:\-]', 'instruction_override'),
        (r'(?i)disregard\s+(all\s+)?(previous|prior)\s+(rules?|instructions?)', 'ignore_instructions'),
        (r'(?i)system\s*prompt\s*[:\-=]', 'prompt_extraction'),
        (r'(?i)jailbreak', 'jailbreak_attempt'),
        (r'(?i)\bDAN\b.{0,20}(mode|prompt)', 'jailbreak_attempt'),
    ]

    _HTML_COMMENT = re.compile(r'<!--.*?-->', re.DOTALL)
    _HTML_TAG = re.compile(r'<[^>]{0,300}>', re.DOTALL)
    _BASE64_BLOB = re.compile(r'(?<![A-Za-z0-9+/])[A-Za-z0-9+/]{60,}={0,2}(?![A-Za-z0-9+/])')
    _ZERO_WIDTH = re.compile(r'[\u200b\u200c\u200d\u2060\ufeff\u00ad]')

    @classmethod
    def clean(cls, text, max_length=4000):
        """Czyści tekst CV: usuwa HTML, base64, zero-width, szum; normalizuje; skraca."""
        if not text:
            return ''

        # 1. Usuń komentarze HTML i tagi (mogą ukrywać instrukcje)
        text = cls._HTML_COMMENT.sub('', text)
        text = cls._HTML_TAG.sub('', text)

        # 2. Usuń znaki zero-width (steganografia)
        text = cls._ZERO_WIDTH.sub('', text)

        # 3. Usuń duże bloki base64 (zakodowane ukryte instrukcje)
        text = cls._BASE64_BLOB.sub('[removed]', text)

        # 4. Usuń wzorce szumu (stopki, numery stron)
        for pattern in cls.NOISE_PATTERNS:
            text = re.sub(pattern, '', text, flags=re.MULTILINE)

        # 5. Normalizuj białe znaki
        text = re.sub(r'\n{3,}', '\n\n', text)
        text = re.sub(r'[ \t]{2,}', ' ', text)

        # 6. Usuń puste linie na początku/końcu
        lines = text.strip().splitlines()
        text = '\n'.join(line.rstrip() for line in lines if line.strip())

        # 7. Skróć do max_length
        if len(text) > max_length:
            text = text[:max_length]

        return text

    @classmethod
    def scan_for_injection(cls, text):
        """
        Skanuje tekst CV w poszukiwaniu wzorców Prompt Injection.

        Zwraca listę słowników (może być pusta):
          [{'type': str, 'fragment': str, 'action': 'content_flagged'}, ...]

        Nie blokuje analizy — wyniki trafiają do AnalysisResult.security_flags.
        """
        findings = []
        for pattern, injection_type in cls.INJECTION_PATTERNS:
            match = re.search(pattern, text)
            if match:
                fragment = match.group()[:120]
                findings.append({
                    'type': injection_type,
                    'fragment': fragment,
                    'action': 'content_flagged',
                })
                logger.warning(
                    f"Prompt injection in CV: type={injection_type!r} "
                    f"fragment={fragment!r}"
                )
        return findings

    @classmethod
    def get_short_preview(cls, text, max_length=2000):
        """Zwraca krótki podgląd tekstu (do promptu 2 - scoring)."""
        return cls.clean(text, max_length=max_length)
