"""analysis/services/text_cleaner.py - Czyszczenie tekstu CV przed wysłaniem do AI.

Optymalizacja: mniejszy input = szybsza odpowiedź AI.
Usuwa stopki, powtórzenia, puste linie, skraca do max 6000 znaków.
"""

import re


class TextCleaner:
    """Czyści i przygotowuje tekst CV do analizy AI."""

    # Wzorce do usuwania (stopki, śmieci, powtórzenia)
    NOISE_PATTERNS = [
        r'Page \d+ of \d+',
        r'Strona \d+ z \d+',
        r'^\s*\d+\s*$',  # samotne numery stron
        r'(?i)curriculum vitae\s*$',
        r'(?i)resume\s*$',
        r'(?i)^generated by.*$',
        r'(?i)^powered by.*$',
        r'(?i)^confidential\s*$',
    ]

    @classmethod
    def clean(cls, text, max_length=4000):
        """Czyści tekst CV: usuwa szum, normalizuje, skraca."""
        if not text:
            return ''

        # Usuń wzorce szumu
        for pattern in cls.NOISE_PATTERNS:
            text = re.sub(pattern, '', text, flags=re.MULTILINE)

        # Normalizuj wielokrotne puste linie -> max 1
        text = re.sub(r'\n{3,}', '\n\n', text)

        # Normalizuj wielokrotne spacje
        text = re.sub(r'[ \t]{2,}', ' ', text)

        # Usuń puste linie na początku i końcu
        lines = text.strip().splitlines()
        cleaned_lines = [line.rstrip() for line in lines if line.strip()]

        text = '\n'.join(cleaned_lines)

        # Skróć do max_length
        if len(text) > max_length:
            text = text[:max_length]

        return text

    @classmethod
    def get_short_preview(cls, text, max_length=2000):
        """Zwraca krótki podgląd tekstu (do promptu 2 - scoring)."""
        cleaned = cls.clean(text, max_length=max_length)
        return cleaned
