# Generated by Django 5.2.7 on 2026-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
