# Generated by Django 5.2.7 on 2026-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvdocument_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='section_type',
            field=models.CharField(choices=[('summary', 'Summary / Profile'), ('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certificates', 'Certificates'), ('languages', 'Languages'), ('contact', 'Contact'), ('interests', 'Interests'), ('other', 'Other')], max_length=30),
        ),
    ]
