# Generated by Django 5.2.12 on 2026-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_add_contact_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='injection_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='injection_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='injection_score',
            field=models.IntegerField(default=0),
        ),
    ]
